Testing
AnsarIbrahim/Math-Magicians pull request #6
Opened 2023-07-12 15:13 UTC by AnsarIbrahim

### This PR contains :
 
- Set up React Testing Library✅
- Write unit tests for the files operate.js and calculate.js using Jest.✅
- Create unit tests for all React components:✅
- Use Jest snapshots to test the components.✅
- Use React Testing Library to simulate user interaction.✅
- Run your full tests suite using Jest. All tests should pass✅

2023-07-12 17:16 UTC, AdnanOlarmmi requested changes
Hi @AnsarIbrahim and @Innocent259, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Well written test, Kudos to you.
- Nice working in pairs, this shows your collaborative skills.

## Required Changes ♻️
- [ ] Please, kindly include your partner's information in the authors section of your readme.
<img width="506" alt="image" src="https://github.com/AnsarIbrahim/Math-Magicians/assets/41163571/1a841dc9-a6bd-4ea0-94f0-43b9e3292bea">

_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 17:16 UTC, AdnanOlarmmi commented on src/test/calculate.test.js
> +    const result = calculate({ total: '10', next: '5', operation: '+' }, '7');
- [ ] Nice one with the tests, according to the requirement, you're supposed to write tests for all scenarios of the calculate.js and the operate.js, the operate.js seems okay, but the following was omitted in the calculate.js

- [ ] You didn't test if the input has a decimal point.

```
 if (buttonName === '.') {
    if (obj.next) {
      if (obj.next.includes('.')) {
        return { ...obj };
      }
      return { ...obj, next: `${obj.next}.` };
    }
    if (obj.operation) {
      return { ...obj, next: '0.' };
    }
    if (obj.total) {
      if (obj.total.includes('.')) {
        return {};
      }
      return { ...obj, next: `${obj.total}.` };
    }
    return { ...obj, next: '0.' };
  }
```

2023-07-12 17:16 UTC, AdnanOlarmmi commented on src/test/calculate.test.js
- [ ] Nice work with the following tests, but according to the project requirement, the test should also simulate user's interaction.

2023-07-13 07:17 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @TEAM  , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Professional README
- [x] No linter errors
- [x] Descriptive P.R
- [x] Tests are running as intended 🥇  🥂 



 
 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

2023-07-13 07:27 UTC, merged